# Generated by Django 5.1.3 on 2024-12-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_alter_trail_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trail',
            options={'ordering': ['pk']},
        ),
    ]
