# Generated by Django 5.1.3 on 2024-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/animal_images')),
                ('common_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('conservation_status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('wikipedia_page', models.URLField(max_length=500)),
                ('additional_info', models.URLField(blank=True, max_length=500, null=True)),
                ('trail', models.ManyToManyField(to='trails.trail')),
            ],
        ),
    ]
