# Generated by Django 5.1.3 on 2024-11-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('trail_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='trail_logs',
            field=models.ManyToManyField(blank=True, to='trail_logs.traillog'),
        ),
    ]
