# Generated by Django 5.1.3 on 2024-11-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('trails', '0002_traillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='trail_logs',
            field=models.ManyToManyField(to='trails.traillog'),
        ),
    ]
