# Generated by Django 5.1.3 on 2024-12-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_trails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['pk']},
        ),
    ]
