# Generated by Django 5.1.3 on 2024-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_trail_logs'),
        ('trails', '0002_traillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='trail_logs',
            field=models.ManyToManyField(blank=True, to='trails.traillog'),
        ),
    ]
