# Generated by Django 5.1.3 on 2024-12-26 20:00

import theOutdoorChronicles.trail_logs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_logs', '0004_remove_traillog_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traillog',
            name='date_completed',
            field=models.DateField(validators=[theOutdoorChronicles.trail_logs.validators.validate_date_not_in_future]),
        ),
    ]
