# Generated by Django 5.1.3 on 2024-11-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_animal_alter_photo_trail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
