# Generated by Django 5.1.3 on 2024-12-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['pk']},
        ),
    ]
